import 'dotenv/config';
import connectDB from '../src/config/db.js';
import Order from '../src/models/Order.model.js';
import { verifyPickup } from '../src/modules/vendor/controllers/order.controller.js';
import { updateDeliveryStatus } from '../src/modules/delivery/controllers/order.controller.js';
import mongoose from 'mongoose';
import crypto from 'crypto';
import Vendor from '../src/models/Vendor.model.js';

const runSimulation = async () => {
    await connectDB();
    console.log('--- Starting Delivery Flow Simulation ---');

    const orderId = 'ORD-1783423050771-NVS3';
    const order = await Order.findOne({ orderId });
    if (!order) {
        console.error('Order not found.');
        process.exit(1);
    }

    const secret = process.env.JWT_SECRET || 'fallback-secret-key';

    // 1. Reset order to ready_for_pickup
    console.log('\n[Step 1] Resetting order to ready_for_pickup...');
    order.status = 'ready_for_pickup';
    order.deliveryAssignmentStatus = 'accepted';
    order.vendorItems = order.vendorItems.map(vi => ({
        ...vi.toObject(),
        status: 'ready_for_pickup'
    }));
    
    // Set pickup OTP
    const pickupOtp = '555519';
    order.pickupOtpHash = crypto.createHash('sha256').update(`${pickupOtp}:${secret}`).digest('hex');
    order.pickupOtpExpiry = new Date(Date.now() + 30 * 60 * 1000);
    order.pickupOtpDebug = pickupOtp;
    
    // Clear delivery OTP
    order.deliveryOtpHash = undefined;
    order.deliveryOtpExpiry = undefined;
    order.deliveryOtpDebug = undefined;
    order.deliveryOtpVerifiedAt = undefined;

    await order.save();
    console.log('Order reset successfully. Status:', order.status, 'Pickup OTP Debug:', order.pickupOtpDebug);

    // 2. Simulate Vendor verifying pickup
    console.log('\n[Step 2] Simulating Vendor verify-pickup with OTP 555519...');
    const req1 = {
        user: { id: '6996c04b4a33b2417858505e' }, // Fashion Hub Store Vendor ID
        params: { id: orderId },
        body: { otp: '555519' }
    };
    const res1 = {
        statusCode: 200,
        status(code) { this.statusCode = code; return this; },
        json(data) {
            console.log('Vendor Verify Response Status:', this.statusCode);
            console.log('Vendor Verify Response Message:', data.message);
        }
    };
    await verifyPickup(req1, res1);

    // Reload order from DB
    let updatedOrder = await Order.findOne({ orderId }).select('+deliveryOtpDebug +deliveryOtpHash +deliveryOtpExpiry');
    console.log('Post-pickup status in DB:', updatedOrder.status);
    console.log('Delivery OTP Debug generated by pre-save:', updatedOrder.deliveryOtpDebug);

    if (!updatedOrder.deliveryOtpDebug) {
        console.error('ERROR: Delivery OTP was not generated!');
        process.exit(1);
    }

    // 3. Simulate Delivery Agent completing delivery
    const deliveryOtp = updatedOrder.deliveryOtpDebug;
    console.log(`\n[Step 3] Simulating Delivery complete with OTP ${deliveryOtp}...`);
    const req2 = {
        user: { id: '69980d681126b3b604b8734b' }, // Delivery Boy ID
        params: { id: orderId },
        body: { status: 'delivered', otp: deliveryOtp }
    };
    const res2 = {
        statusCode: 200,
        status(code) { this.statusCode = code; return this; },
        json(data) {
            console.log('Delivery Complete Response Status:', this.statusCode);
            console.log('Delivery Complete Response Message:', data.message);
        }
    };
    await updateDeliveryStatus(req2, res2);

    // Reload order from DB
    updatedOrder = await Order.findOne({ orderId });
    console.log('\nFinal order status in DB:', updatedOrder.status);

    await mongoose.disconnect();
    console.log('--- Simulation Finished ---');
};

runSimulation().catch(console.error);
